trigger:
  - feature

pool:
  name: 'AgentUserDefinedPool'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'anuj-pipeline-sc'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd INFRA-01
        terraform init
        terraform fmt
        terraform validate
        terraform plan